[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node api/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 10

[[services]]
name = "api"
protocol = "http"
port = "3001"

[[volumes]]
name = "data"
mountPath = "/data" 