[build]
builder = "nixpacks"
buildCommand = "npm install && ls -la && pwd && echo 'Contents of root:' && ls -R"

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"

[[services]]
name = "api"
protocol = "http"
port = "3001"

[[volumes]]
name = "data"
mountPath = "/data" 